# Generated by Django 5.0.2 on 2026-03-10 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado'),
        ),
        migrations.AddField(
            model_name='ticketasignacionhistorial',
            name='asignado_a_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
        migrations.AddField(
            model_name='ticketasignacionhistorial',
            name='asignado_por_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por'),
        ),
        migrations.AddField(
            model_name='ticketasignacionhistorial',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asignaciones', to='tickets.ticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='ticketestadohistorial',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='tickets.ticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='ticketestadohistorial',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='ticket_estado_e074a5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['area', 'estado'], name='ticket_area_id_d06d35_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['usuario_asignado', 'estado'], name='ticket_usuario_326971_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketasignacionhistorial',
            index=models.Index(fields=['ticket', '-fecha_asignacion'], name='ticket_asig_ticket__c8f541_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketasignacionhistorial',
            index=models.Index(fields=['asignado_a_usuario', '-fecha_asignacion'], name='ticket_asig_asignad_d9a084_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketestadohistorial',
            index=models.Index(fields=['ticket', '-fecha'], name='ticket_esta_ticket__1f2b39_idx'),
        ),
    ]
