# Generated by Django 5.0.2 on 2026-03-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemaforoSLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(default='Configuración Global', max_length=100, unique=True, verbose_name='Nombre de la configuración')),
                ('warning_percentage', models.PositiveIntegerField(default=80, help_text='Al llegar a este porcentaje del tiempo SLA, cambia a amarillo.', verbose_name='Porcentaje de alerta (amarillo)')),
                ('danger_percentage', models.PositiveIntegerField(default=100, help_text='Al llegar a este porcentaje del tiempo SLA, cambia a rojo.', verbose_name='Porcentaje crítico (rojo)')),
            ],
            options={
                'verbose_name': 'Configuración de Semáforo SLA',
                'verbose_name_plural': 'Configuración de Semáforo SLA',
                'db_table': 'semaforo_sla_config',
            },
        ),
    ]
