# Generated by Django 5.0.2 on 2026-03-18 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Área a la que pertenece el usuario (requerido para operativos y jefes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='tickets.area', verbose_name='Área'),
        ),
    ]
